### PR TITLE
Bugfix/202 better status codes on rest errors

### LINKED ISSUE #202: Fix inappropriate Authentication results during REST calls
On heavy server load and with a groups starting around 400 accounts, the `sync`-ful creation or deletion (`/api/users?sync=true` etc) from said group may return in unexpected authentication results `HTTP 401 Unauthorized` when a result `HTTP 500 Internal server errror` is more appropriate.

### PR DESCRIPTION
**Pull request by ppxl**
This PR resolves #202 by handling exceptions as runtime exceptions rather than blindly throwing Cas Auth exceptions around.

### CODE REVIEW

File: app/src/main/java/de/triology/universeadm/CasRestClient.java [hunk 1]
```diff
@@ -5,379 +5,323 @@
...
+        try {
+            String tgt = createGrantingTicket(casServerUrl, username, password);
+
+            logger.debug("TGT is: {}", tgt);
+
+            st = createServiceTicket(tgt);
+
+            logger.debug("ST is: {}", st);
+        } catch (IOException ex) {
+            throw new RuntimeException("cas validation failed", ex);
```
Comment (cloudgge) [inline app/src/main/java/de/triology/universeadm/CasRestClient.java]: Is this related to your fix? I would have expected a CasAuthenticationException is more fitting here.

Comment (cloudgge) [inline app/src/main/java/de/triology/universeadm/CasRestClient.java]: I think I would have preferred for us to extend CAS Apereos AbstractTicketException class and make custom Ticketing exceptions that we could map to proper http codes instead of a blanket 500. But I think our Java version is so old that we would have to use some very old cas version of  [CAS Server Core API Ticket](https://mvnrepository.com/artifact/org.apereo.cas/cas-server-core-api-ticket).

**Review by cloudgge — COMMENTED** [review]
I'd say this looks pretty good. I highly value your initiative in fixing the comments and adding proper documentation where it was lacking.

File: app/src/main/java/de/triology/universeadm/CasRestClient.java (hunk 1 above)
Comment (ppxl) [reply app/src/main/java/de/triology/universeadm/CasRestClient.java]: I see your line of tinking and I would have accepted suggestions for other exception classes. 

Anyhow, the exceptions in question *do not have anything to do* with CAS problems. CasExceptions DO have their place here and in other classes but wrapping non-CAS exceptions into something Ticket-y would lead to the wrong assumption. 

`HTTP 500 internal server error` is in my book the _perfect result_ for errors that happen during serving and encountering problems that could not match to any other status code. 

Here, Usermgt requested the LDAP for modification but the LDAP didn't comply in time. That is not a Ticket exception. That is something so out of scope for business and techical reasons, that HTTP 500 is the best bet. We cannot have this exception handled in any way rather than retrying 30 seconds more and alone this fact is basically unacceptable in terms of HTTP requests.

Comment (ppxl) [reply app/src/main/java/de/triology/universeadm/CasRestClient.java]: Yes, I concur this is a bit misleading. But for REST CAS interaction, this is a basic workflow to get a fresh TGT in order to create a new ST.
